export const CityEnum = Object.freeze({
  臺北市: 'Taipei',
  新北市: 'NewTaipei',
  桃園市: 'Taoyuan',
  臺中市: 'Taichung',
  臺南市: 'Tainan',
  高雄市: 'Kaohsiung',
  基隆市: 'Keelung',
  新竹市: 'Hsinchu',
  新竹縣: 'HsinchuCounty',
  苗栗縣: 'MiaoliCounty',
  彰化縣: 'ChanghuaCounty',
  南投縣: 'NantouCounty',
  雲林縣: 'YunlinCounty',
  嘉義縣: 'ChiayiCounty',
  嘉義市: 'Chiayi',
  屏東縣: 'PingtungCounty',
  宜蘭縣: 'YilanCounty',
  花蓮縣: 'HualienCounty',
  臺東縣: 'TaitungCounty',
  金門縣: 'KinmenCounty',
  澎湖縣: 'PenghuCounty',
  連江縣: 'LienchiangCounty',
})

export const City = {
  [CityEnum.臺北市]: '臺北市',
  [CityEnum.新北市]: '新北市',
  [CityEnum.桃園市]: '桃園市',
  [CityEnum.臺中市]: '臺中市',
  [CityEnum.臺南市]: '臺南市',
  [CityEnum.高雄市]: '高雄市',
  [CityEnum.基隆市]: '基隆市',
  [CityEnum.新竹市]: '新竹市',
  [CityEnum.新竹縣]: '新竹縣',
  [CityEnum.苗栗縣]: '苗栗縣',
  [CityEnum.彰化縣]: '彰化縣',
  [CityEnum.南投縣]: '南投縣',
  [CityEnum.雲林縣]: '雲林縣',
  [CityEnum.嘉義縣]: '嘉義縣',
  [CityEnum.嘉義市]: '嘉義市',
  [CityEnum.屏東縣]: '屏東縣',
  [CityEnum.宜蘭縣]: '宜蘭縣',
  [CityEnum.花蓮縣]: '花蓮縣',
  [CityEnum.臺東縣]: '臺東縣',
  [CityEnum.金門縣]: '金門縣',
  [CityEnum.澎湖縣]: '澎湖縣',
  [CityEnum.連江縣]: '連江縣',
}
